name: First pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet build
  displayName: 'Build the solution'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(60c357c4-1df7-4bca-847f-c0ae1ab27be9)'
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

